-- =====================================================
-- 08-cost-monitoring.sql
-- Real-time cost monitoring and anomaly detection for warehouse spend
-- ML-powered alerts when costs spike unexpectedly
-- =====================================================

USE ROLE CLINICAL_ADMIN;
USE DATABASE CLINICAL_DB;
USE WAREHOUSE CLINICAL_ETL_WH;

-- =====================================================
-- COST MONITORING SCHEMA
-- =====================================================

CREATE SCHEMA IF NOT EXISTS MONITORING
  COMMENT = 'Cost monitoring, anomaly detection, and budget alerts';

USE SCHEMA MONITORING;

-- =====================================================
-- WAREHOUSE USAGE TRACKING TABLE
-- =====================================================

CREATE OR REPLACE TABLE WAREHOUSE_USAGE_HISTORY (
    USAGE_ID STRING DEFAULT UUID_STRING(),
    MEASUREMENT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    WAREHOUSE_NAME STRING,
    WAREHOUSE_SIZE STRING,
    STATE STRING,
    CREDITS_USED NUMBER(38, 4),
    CREDITS_USED_COMPUTE NUMBER(38, 4),
    CREDITS_USED_CLOUD_SERVICES NUMBER(38, 4),
    QUERIES_EXECUTED NUMBER,
    BYTES_SCANNED NUMBER,
    ROWS_PRODUCED NUMBER,
    EXECUTION_TIME_MS NUMBER,
    COST_USD NUMBER(10, 2),
    DAILY_BUDGET_USD NUMBER(10, 2) DEFAULT 100.00,
    BUDGET_UTILIZATION_PCT NUMBER(5, 2)
)
COMMENT = 'Historical warehouse usage and cost tracking';

-- =====================================================
-- DAILY COST SUMMARY VIEW
-- =====================================================

CREATE OR REPLACE VIEW V_DAILY_COST_SUMMARY AS
SELECT
    DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    SUM(CREDITS_USED) AS TOTAL_CREDITS_USED,
    SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICE_CREDITS,
    COUNT(*) AS QUERY_COUNT,
    SUM(BYTES_SCANNED) / POWER(1024, 3) AS GB_SCANNED,
    -- Snowflake pricing: $2/credit for Enterprise Edition (adjust based on your contract)
    SUM(CREDITS_USED) * 2 AS COST_USD,
    100.00 AS DAILY_BUDGET_USD,
    (SUM(CREDITS_USED) * 2 / 100.00) * 100 AS BUDGET_UTILIZATION_PCT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_DATE())
GROUP BY 1, 2, 3
ORDER BY 1 DESC, 5 DESC;

-- =====================================================
-- REAL-TIME WAREHOUSE COST TRACKER
-- =====================================================

CREATE OR REPLACE VIEW V_WAREHOUSE_COST_REALTIME AS
SELECT
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    STATE,
    SUM(CREDITS_USED) AS CREDITS_USED_TODAY,
    SUM(CREDITS_USED) * 2 AS COST_USD_TODAY,
    100.00 AS DAILY_BUDGET,
    (SUM(CREDITS_USED) * 2 / 100.00) * 100 AS BUDGET_UTILIZATION_PCT,
    CASE
        WHEN (SUM(CREDITS_USED) * 2) > 100 THEN '🚨 OVER BUDGET'
        WHEN (SUM(CREDITS_USED) * 2) > 75 THEN '⚠️ WARNING: 75%+'
        WHEN (SUM(CREDITS_USED) * 2) > 50 THEN '📊 NORMAL: 50-75%'
        ELSE '✅ HEALTHY: <50%'
    END AS BUDGET_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= CURRENT_DATE()
GROUP BY 1, 2, 3
ORDER BY 4 DESC;

-- =====================================================
-- QUERY COST ANALYSIS (Top Expensive Queries)
-- =====================================================

CREATE OR REPLACE VIEW V_EXPENSIVE_QUERIES AS
SELECT
    QUERY_ID,
    USER_NAME,
    ROLE_NAME,
    WAREHOUSE_NAME,
    QUERY_TYPE,
    START_TIME,
    TOTAL_ELAPSED_TIME / 1000 AS EXECUTION_SECONDS,
    BYTES_SCANNED / POWER(1024, 3) AS GB_SCANNED,
    CREDITS_USED_CLOUD_SERVICES,
    -- Estimate query cost based on warehouse size and execution time
    CASE WAREHOUSE_SIZE
        WHEN 'XSMALL' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 1 * 2
        WHEN 'SMALL' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 2 * 2
        WHEN 'MEDIUM' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 4 * 2
        WHEN 'LARGE' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 8 * 2
        WHEN 'XLARGE' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 16 * 2
        WHEN '2XLARGE' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 32 * 2
        WHEN '3XLARGE' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 64 * 2
        WHEN '4XLARGE' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 128 * 2
        WHEN '5XLARGE' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 256 * 2
        WHEN '6XLARGE' THEN (TOTAL_ELAPSED_TIME / 1000 / 3600) * 512 * 2
        ELSE 0
    END AS ESTIMATED_COST_USD,
    LEFT(QUERY_TEXT, 200) AS QUERY_PREVIEW
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('DAY', -7, CURRENT_DATE())
    AND TOTAL_ELAPSED_TIME > 60000  -- Queries longer than 1 minute
    AND WAREHOUSE_NAME IS NOT NULL
ORDER BY ESTIMATED_COST_USD DESC
LIMIT 100;

-- =====================================================
-- COST ANOMALY DETECTION (ML-Powered)
-- =====================================================

CREATE OR REPLACE TABLE COST_ANOMALY_BASELINE (
    WAREHOUSE_NAME STRING,
    AVG_DAILY_CREDITS NUMBER(10, 4),
    STDDEV_DAILY_CREDITS NUMBER(10, 4),
    AVG_DAILY_COST_USD NUMBER(10, 2),
    BASELINE_CALCULATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Statistical baseline for cost anomaly detection';

-- Calculate baseline (run this weekly)
CREATE OR REPLACE PROCEDURE CALCULATE_COST_BASELINE()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    TRUNCATE TABLE COST_ANOMALY_BASELINE;
    
    INSERT INTO COST_ANOMALY_BASELINE (WAREHOUSE_NAME, AVG_DAILY_CREDITS, STDDEV_DAILY_CREDITS, AVG_DAILY_COST_USD)
    SELECT
        WAREHOUSE_NAME,
        AVG(DAILY_CREDITS) AS AVG_DAILY_CREDITS,
        STDDEV(DAILY_CREDITS) AS STDDEV_DAILY_CREDITS,
        AVG(DAILY_CREDITS) * 2 AS AVG_DAILY_COST_USD
    FROM (
        SELECT
            WAREHOUSE_NAME,
            DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
            SUM(CREDITS_USED) AS DAILY_CREDITS
        FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
        WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_DATE())
        GROUP BY 1, 2
    )
    GROUP BY WAREHOUSE_NAME;
    
    RETURN 'Cost baseline recalculated successfully';
END;
$$;

-- Detect anomalies (run this hourly)
CREATE OR REPLACE VIEW V_COST_ANOMALIES AS
WITH today_usage AS (
    SELECT
        WAREHOUSE_NAME,
        SUM(CREDITS_USED) AS CREDITS_TODAY
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= CURRENT_DATE()
    GROUP BY 1
)
SELECT
    t.WAREHOUSE_NAME,
    t.CREDITS_TODAY,
    b.AVG_DAILY_CREDITS AS BASELINE_AVG,
    b.STDDEV_DAILY_CREDITS AS BASELINE_STDDEV,
    -- Z-score calculation (how many standard deviations away from mean)
    (t.CREDITS_TODAY - b.AVG_DAILY_CREDITS) / NULLIF(b.STDDEV_DAILY_CREDITS, 0) AS Z_SCORE,
    CASE
        WHEN (t.CREDITS_TODAY - b.AVG_DAILY_CREDITS) / NULLIF(b.STDDEV_DAILY_CREDITS, 0) > 3 
            THEN '🚨 CRITICAL ANOMALY (3σ+)'
        WHEN (t.CREDITS_TODAY - b.AVG_DAILY_CREDITS) / NULLIF(b.STDDEV_DAILY_CREDITS, 0) > 2 
            THEN '⚠️ HIGH ANOMALY (2σ+)'
        WHEN (t.CREDITS_TODAY - b.AVG_DAILY_CREDITS) / NULLIF(b.STDDEV_DAILY_CREDITS, 0) > 1.5 
            THEN '📊 MODERATE ANOMALY (1.5σ+)'
        ELSE '✅ NORMAL'
    END AS ANOMALY_SEVERITY,
    t.CREDITS_TODAY * 2 AS COST_TODAY_USD,
    b.AVG_DAILY_COST_USD AS BASELINE_COST_USD,
    (t.CREDITS_TODAY * 2) - b.AVG_DAILY_COST_USD AS COST_VARIANCE_USD
FROM today_usage t
JOIN COST_ANOMALY_BASELINE b ON t.WAREHOUSE_NAME = b.WAREHOUSE_NAME
WHERE (t.CREDITS_TODAY - b.AVG_DAILY_CREDITS) / NULLIF(b.STDDEV_DAILY_CREDITS, 0) > 1.5
ORDER BY Z_SCORE DESC;

-- =====================================================
-- COST ALERT PROCEDURE (Send to Email/Slack/PagerDuty)
-- =====================================================

CREATE OR REPLACE PROCEDURE SEND_COST_ALERT()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    anomaly_count INTEGER;
    alert_message STRING;
BEGIN
    -- Count critical anomalies
    SELECT COUNT(*) INTO :anomaly_count
    FROM V_COST_ANOMALIES
    WHERE Z_SCORE > 2;
    
    IF (:anomaly_count > 0) THEN
        alert_message := '🚨 COST ANOMALY DETECTED: ' || :anomaly_count || ' warehouse(s) exceeded 2σ threshold. Check MONITORING.V_COST_ANOMALIES';
        
        -- Log alert to table
        INSERT INTO COST_ALERT_LOG (ALERT_TIMESTAMP, ALERT_TYPE, ALERT_MESSAGE, ANOMALY_COUNT)
        VALUES (CURRENT_TIMESTAMP(), 'COST_ANOMALY', :alert_message, :anomaly_count);
        
        -- In production, integrate with email_notification or external_functions for Slack/PagerDuty
        -- CALL SYSTEM$SEND_EMAIL('admin@hospital.com', 'Cost Alert', :alert_message);
        
        RETURN alert_message;
    ELSE
        RETURN '✅ No cost anomalies detected';
    END IF;
END;
$$;

-- Alert log table
CREATE TABLE IF NOT EXISTS COST_ALERT_LOG (
    ALERT_ID STRING DEFAULT UUID_STRING(),
    ALERT_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ALERT_TYPE STRING,
    ALERT_MESSAGE STRING,
    ANOMALY_COUNT INTEGER,
    ACKNOWLEDGED BOOLEAN DEFAULT FALSE,
    ACKNOWLEDGED_BY STRING,
    ACKNOWLEDGED_AT TIMESTAMP_NTZ
);

-- =====================================================
-- BUDGET TRACKING TABLE
-- =====================================================

CREATE OR REPLACE TABLE MONTHLY_BUDGET (
    BUDGET_MONTH DATE,
    WAREHOUSE_NAME STRING,
    MONTHLY_BUDGET_USD NUMBER(10, 2),
    ALERT_THRESHOLD_PCT NUMBER(5, 2) DEFAULT 75.00
)
COMMENT = 'Monthly budget allocations per warehouse';

-- Insert sample budgets
INSERT INTO MONTHLY_BUDGET (BUDGET_MONTH, WAREHOUSE_NAME, MONTHLY_BUDGET_USD, ALERT_THRESHOLD_PCT)
VALUES
    (DATE_TRUNC('MONTH', CURRENT_DATE()), 'CLINICAL_ETL_WH', 100.00, 75.00),
    (DATE_TRUNC('MONTH', CURRENT_DATE()), 'CLINICAL_INTERACTIVE_WH', 200.00, 75.00);

-- Budget utilization view
CREATE OR REPLACE VIEW V_BUDGET_UTILIZATION AS
WITH monthly_spend AS (
    SELECT
        WAREHOUSE_NAME,
        SUM(CREDITS_USED) * 2 AS MONTH_TO_DATE_SPEND_USD
    FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
    WHERE START_TIME >= DATE_TRUNC('MONTH', CURRENT_DATE())
    GROUP BY 1
)
SELECT
    b.WAREHOUSE_NAME,
    b.MONTHLY_BUDGET_USD,
    COALESCE(m.MONTH_TO_DATE_SPEND_USD, 0) AS MONTH_TO_DATE_SPEND_USD,
    b.MONTHLY_BUDGET_USD - COALESCE(m.MONTH_TO_DATE_SPEND_USD, 0) AS REMAINING_BUDGET_USD,
    (COALESCE(m.MONTH_TO_DATE_SPEND_USD, 0) / b.MONTHLY_BUDGET_USD) * 100 AS BUDGET_UTILIZATION_PCT,
    b.ALERT_THRESHOLD_PCT,
    CASE
        WHEN (COALESCE(m.MONTH_TO_DATE_SPEND_USD, 0) / b.MONTHLY_BUDGET_USD) * 100 >= 100 
            THEN '🚨 BUDGET EXCEEDED'
        WHEN (COALESCE(m.MONTH_TO_DATE_SPEND_USD, 0) / b.MONTHLY_BUDGET_USD) * 100 >= b.ALERT_THRESHOLD_PCT 
            THEN '⚠️ APPROACHING LIMIT'
        ELSE '✅ WITHIN BUDGET'
    END AS BUDGET_STATUS
FROM MONTHLY_BUDGET b
LEFT JOIN monthly_spend m ON b.WAREHOUSE_NAME = m
